version: '3.9'

services:
  finance-db:
    image: postgres:15
    container_name: finance-platform-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: financepass
      POSTGRES_DB: finance_platform
    ports:
      - "6544:5432"
    volumes:
      - finance-platform-postgres-data:/var/lib/postgresql/data

volumes:
  finance-platform-postgres-data:
